import { useState } from "react";
import {
  Activity, BarChart3, Bell, BookOpen, Building2, CalendarDays, ChevronDown,
  ChevronRight, CircleHelp, ClipboardCheck, Clock3, Command, FileQuestion,
  Filter, Gauge, HandCoins, LayoutDashboard, ListFilter, Menu, MoreHorizontal,
  Plus, Search, Settings2, ShieldCheck, SlidersHorizontal, Timer, UsersRound,
  Wrench, X, AlertTriangle, Lightbulb, CircleDot, ArrowUpRight, Layers3, PanelTop, Send, CheckCircle2, FileText
} from "lucide-react";

type Navigation = { label: string; icon: typeof LayoutDashboard; count?: string };
const operations: Navigation[] = [
  { label: "Visão geral", icon: LayoutDashboard }, { label: "Chamados", icon: CircleDot, count: "24" },
  { label: "Minha fila", icon: ListFilter, count: "7" }, { label: "Aprovação de horas", icon: ClipboardCheck, count: "9" },
];
const management: Navigation[] = [{ label: "Clientes", icon: Building2 }, { label: "Usuários", icon: UsersRound }, { label: "Relatórios", icon: BarChart3 }];
const tickets = [
  ["INC-1842", "Integração com ERP retorna erro 502", "Vértice Logística", "Incidente", "Crítica", "AR", "12 min", "Em atendimento"],
  ["REQ-1839", "Revisar permissões do painel financeiro", "Norte & Co.", "Requisição", "Alta", "MS", "36 min", "Aguardando cliente"],
  ["PRB-1837", "Lentidão na importação de planilhas", "Aurora Foods", "Problema", "Alta", "JL", "1 h", "Investigação"],
  ["MEL-1834", "Adicionar campo de centro de custo", "Cobalto Energia", "Melhoria", "Média", "RP", "2 h", "Em análise"],
  ["DUV-1828", "Dúvida sobre relatório consolidado", "Grupo Praxis", "Dúvida", "Baixa", "AC", "Ontem", "Resolvido"],
];
const lifecycle = [
  ["Incidentes", "Interrupção não planejada", 8, AlertTriangle, "#bd1f2d"],
  ["Requisições", "Acesso, serviço ou informação", 7, HandCoins, "#556266"],
  ["Problemas", "Causa raiz em análise", 4, Wrench, "#d77a45"],
  ["Melhorias", "Evoluções priorizadas", 3, Lightbulb, "#82758a"],
  ["Dúvidas", "Orientação e suporte", 2, FileQuestion, "#8d9a9d"],
] as const;

function SideItem({ item, selected, setSelected }: { item: Navigation; selected: string; setSelected: (s: string) => void }) {
  const Icon = item.icon;
  return <button onClick={() => setSelected(item.label)} className={`flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-[13px] transition ${selected === item.label ? "bg-primary text-white shadow-sm" : "text-[#c7c9c9] hover:bg-white/10 hover:text-white"}`}><Icon size={16} /><span className="flex-1">{item.label}</span>{item.count && <span className="font-['DM_Mono'] text-[10px] opacity-75">{item.count}</span>}</button>;
}


function ClientPortal({ returnToOperations }: { returnToOperations: () => void }) {
  const [newTicket, setNewTicket] = useState(false);
  const [selectedType, setSelectedType] = useState("Incidente");
  const types = [
    ["Incidente", "Algo parou ou não está funcionando", AlertTriangle, "#bd1f2d"],
    ["Requisição", "Peça um acesso, serviço ou alteração", HandCoins, "#536062"],
    ["Problema", "Reporte uma falha recorrente", Wrench, "#bd7b3e"],
    ["Melhoria", "Sugira uma evolução para o serviço", Lightbulb, "#786b86"],
    ["Dúvida", "Tire uma dúvida sobre a plataforma", FileQuestion, "#607a80"],
  ] as const;
  const clientTickets = [
    ["INC-1842", "Integração com ERP retorna erro 502", "Em atendimento", "Hoje, 09:42", "Crítica"],
    ["REQ-1819", "Acesso para nova colaboradora", "Aguardando sua resposta", "Ontem, 15:30", "Média"],
    ["MEL-1795", "Exportação com novos campos", "Em análise", "03 Out, 10:20", "Baixa"],
  ];
  return <main className="min-h-screen bg-[#f4f4f2] font-['Manrope'] text-[#24282a]">
    <header className="border-b border-[#deded9] bg-white"><div className="mx-auto flex h-[74px] max-w-[1360px] items-center px-5 sm:px-8"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-md bg-primary text-white"><Command size={19}/></div><div><p className="text-[17px] font-extrabold tracking-[-.04em]">nexo<span className="text-primary">.service</span></p><p className="font-['DM_Mono'] text-[9px] uppercase tracking-[.16em] text-[#717777]">portal do cliente</p></div></div><nav className="ml-12 hidden items-center gap-7 text-[12px] font-semibold text-[#5f6667] md:flex"><button className="text-primary">Início</button><button>Meus chamados</button><button>Base de conhecimento</button></nav><div className="ml-auto flex items-center gap-3"><button onClick={returnToOperations} className="hidden items-center gap-1.5 text-[10px] font-bold text-[#626a6b] hover:text-primary sm:flex"><PanelTop size={14}/>Visão consultoria</button><button className="relative grid size-9 place-items-center rounded-md border border-border"><Bell size={16}/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary"/></button><div className="flex items-center gap-2 border-l border-border pl-3"><div className="grid size-8 place-items-center rounded-full bg-[#334e5c] text-[10px] font-bold text-white">VL</div><span className="hidden text-[11px] font-bold sm:block">Vértice Logística</span><ChevronDown size={14}/></div></div></div></header>
    <div className="mx-auto max-w-[1360px] px-5 py-8 sm:px-8"><div className="relative overflow-hidden rounded-xl bg-[#2a2e30] px-6 py-8 text-white sm:px-9"><div className="absolute -right-8 -top-8 size-56 rounded-full border border-white/10"/><div className="absolute right-20 top-12 size-16 rounded-full border border-primary/60"/><p className="font-['DM_Mono'] text-[10px] uppercase tracking-[.16em] text-[#ed767e]">Ambiente seguro · Vértice Logística</p><div className="mt-3 flex flex-col items-start justify-between gap-6 md:flex-row md:items-end"><div><h1 className="font-['Newsreader'] text-[37px] leading-none tracking-[-.035em] sm:text-[44px]">Como podemos ajudar?</h1><p className="mt-3 text-[13px] text-[#c9cdcd]">Abra um chamado ou acompanhe os serviços da sua empresa.</p></div><button onClick={() => setNewTicket(true)} className="relative flex items-center gap-2 rounded-md bg-primary px-4 py-3 text-xs font-bold text-white shadow-lg"><Plus size={16}/>Abrir chamado</button></div></div>
      <div className="mt-7 grid gap-7 xl:grid-cols-[1.5fr_.78fr]"><section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-[18px] font-bold">Meus chamados</h2><p className="mt-1 text-[11px] text-muted-foreground">Visível apenas para usuários da Vértice Logística</p></div><button className="flex items-center gap-1 text-[11px] font-bold text-primary">Ver todos <ArrowUpRight size={13}/></button></div><div className="overflow-hidden rounded-lg border border-border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="bg-[#f8f8f6] font-['DM_Mono'] text-[9px] uppercase tracking-[.13em] text-[#707676]"><tr><th className="px-5 py-3 font-normal">Chamado</th><th className="px-3 py-3 font-normal">Prioridade</th><th className="px-3 py-3 font-normal">Atualização</th><th className="px-5 py-3 text-right font-normal">Situação</th></tr></thead><tbody>{clientTickets.map(([id,title,status,date,priority])=><tr key={id} className="border-t border-border"><td className="px-5 py-4"><p className="font-['DM_Mono'] text-[10px] text-primary">{id}</p><p className="mt-1 text-xs font-bold">{title}</p></td><td className="px-3 py-4 text-[10px] text-[#6c7373]">{priority}</td><td className="px-3 py-4 text-[10px] text-[#6c7373]">{date}</td><td className="px-5 py-4 text-right"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${status==="Em atendimento"?"bg-[#f7e7e8] text-primary":"bg-[#eef0ed] text-[#52605a]"}`}>{status}</span></td></tr>)}</tbody></table></div></div></section>
        <aside className="rounded-lg border border-border bg-white p-5"><div className="flex items-start justify-between"><div><h2 className="text-[15px] font-bold">Acompanhamento</h2><p className="mt-1 text-[11px] text-muted-foreground">Resumo da sua empresa</p></div><Gauge size={18} className="text-primary"/></div><div className="mt-6 divide-y divide-border"><div className="flex justify-between py-3"><span className="text-[11px] text-[#5b6364]">Chamados em aberto</span><b className="font-['DM_Mono'] text-sm">03</b></div><div className="flex justify-between py-3"><span className="text-[11px] text-[#5b6364]">SLA do mês</span><b className="font-['DM_Mono'] text-sm text-primary">96,2%</b></div><div className="flex justify-between py-3"><span className="text-[11px] text-[#5b6364]">Última atualização</span><b className="text-[11px]">Hoje, 10:18</b></div></div><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-md border border-border py-2.5 text-[11px] font-bold text-[#4d5657]"><BookOpen size={14}/>Consultar base de conhecimento</button></aside></div>
      <section className="mt-8"><div className="mb-4"><h2 className="text-[18px] font-bold">Precisa abrir um chamado?</h2><p className="mt-1 text-[11px] text-muted-foreground">Escolha a categoria mais próxima. Nossa equipe direcionará sua solicitação.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{types.map(([name,desc,Icon,color])=>{const I=Icon;return <button onClick={()=>{setSelectedType(name);setNewTicket(true)}} key={name} className="group rounded-lg border border-border bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-primary hover:shadow-sm"><span className="grid size-8 place-items-center rounded-md bg-[#f0f0ed]" style={{color}}><I size={16}/></span><p className="mt-4 text-xs font-bold">{name}</p><p className="mt-1 text-[10px] leading-relaxed text-muted-foreground">{desc}</p><span className="mt-4 flex items-center gap-1 text-[10px] font-bold text-primary opacity-0 transition group-hover:opacity-100">Selecionar <ChevronRight size={12}/></span></button>})}</div></section>
      <section className="mt-8 grid gap-4 border-t border-border pt-7 md:grid-cols-3">{[["Acesso segregado", "Sua empresa visualiza exclusivamente seus próprios chamados, anexos e histórico.", ShieldCheck],["Comunicação centralizada", "Responda atualizações, envie anexos e acompanhe cada etapa em um único lugar.", Send],["Acompanhamento transparente", "Veja prioridade, SLA e o status atual de cada solicitação.", CheckCircle2]].map(([title,desc,Icon])=>{const I=Icon as typeof ShieldCheck;return <div key={String(title)} className="flex gap-3"><I size={17} className="mt-0.5 text-primary"/><div><p className="text-[12px] font-bold">{title as string}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{desc as string}</p></div></div>})}</section>
    </div>
    {newTicket && <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#1e2223]/45 p-4 backdrop-blur-sm sm:items-center"><div className="w-full max-w-[660px] overflow-hidden rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div><p className="font-['DM_Mono'] text-[9px] uppercase tracking-[.14em] text-primary">Vértice Logística</p><h2 className="mt-1 text-[19px] font-bold">Abrir novo chamado</h2></div><button onClick={()=>setNewTicket(false)} className="grid size-8 place-items-center rounded-md bg-[#f0f0ed]"><X size={16}/></button></div><div className="space-y-5 p-6"><div><label className="text-[11px] font-bold">Tipo de chamado</label><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5">{types.map(([name,,Icon,color])=>{const I=Icon;return <button onClick={()=>setSelectedType(name)} key={name} className={`rounded-md border p-2 text-center text-[10px] font-semibold ${selectedType===name?"border-primary bg-[#f7e7e8] text-primary":"border-border text-[#626a6b]"}`}><I size={15} className="mx-auto mb-1" style={{color}}/>{name}</button>})}</div></div><div><label className="text-[11px] font-bold">Assunto</label><input placeholder="Descreva brevemente o que você precisa" className="mt-2 h-10 w-full rounded-md border border-border px-3 text-xs outline-none focus:border-primary"/></div><div><label className="text-[11px] font-bold">Detalhes</label><textarea placeholder="Inclua contexto, impacto e o que já foi tentado." className="mt-2 h-24 w-full resize-none rounded-md border border-border p-3 text-xs outline-none focus:border-primary"/></div><div className="flex items-center justify-between border-t border-border pt-4"><span className="flex items-center gap-1.5 text-[10px] text-muted-foreground"><ShieldCheck size={14} className="text-primary"/>Chamado vinculado à Vértice Logística</span><button onClick={()=>setNewTicket(false)} className="rounded-md bg-primary px-4 py-2.5 text-xs font-bold text-white">Enviar chamado</button></div></div></div></div>}
  </main>;
}

export default function App() {
  const [selected, setSelected] = useState("Visão geral");
  const [menu, setMenu] = useState(false);
  const [period, setPeriod] = useState("Semana");
  const [managementOpen, setManagementOpen] = useState(true);
  const [portalView, setPortalView] = useState(false);
  if (portalView) return <ClientPortal returnToOperations={() => setPortalView(false)} />;
  return <main className="min-h-screen bg-background font-['Manrope'] text-foreground selection:bg-primary selection:text-white">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[258px] flex-col bg-sidebar px-3 py-5 shadow-2xl transition-transform lg:translate-x-0 ${menu ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="mb-8 flex items-center gap-3 px-2"><div className="grid size-9 place-items-center rounded-md bg-primary text-white"><Command size={20}/></div><div><p className="text-[17px] font-extrabold tracking-[-.04em] text-white">nexo<span className="text-[#e4545e]">.service</span></p><p className="font-['DM_Mono'] text-[9px] uppercase tracking-[.18em] text-[#9ca1a0]">IT service management</p></div><button onClick={() => setMenu(false)} className="ml-auto text-white lg:hidden"><X size={18}/></button></div>
      <p className="mb-2 px-3 font-['DM_Mono'] text-[9px] uppercase tracking-[.16em] text-[#89908e]">Operação</p>
      <nav className="space-y-1">{operations.map((item) => <SideItem key={item.label} item={item} selected={selected} setSelected={setSelected}/>)}</nav>
      <div className="mt-7"><button onClick={() => setManagementOpen(!managementOpen)} className="flex w-full items-center px-3 py-2 font-['DM_Mono'] text-[9px] uppercase tracking-[.16em] text-[#89908e]"><span className="flex-1 text-left">Gestão</span><ChevronDown size={13} className={`transition ${managementOpen ? "rotate-180" : ""}`}/></button>{managementOpen && <nav className="mt-1 space-y-1">{management.map((item) => <SideItem key={item.label} item={item} selected={selected} setSelected={setSelected}/>)}<div className="ml-6 mt-2 space-y-1 border-l border-white/15 pl-3"><button onClick={() => setSelected("SLA & Baseline")} className={`block w-full py-1.5 text-left text-[11px] ${selected === "SLA & Baseline" ? "text-[#ef747c]" : "text-[#aab0ae] hover:text-white"}`}>SLA & Baseline</button><button onClick={() => setSelected("Catálogo de serviços")} className="block w-full py-1.5 text-left text-[11px] text-[#aab0ae] hover:text-white">Catálogo de serviços</button></div></nav>}</div>
      <div className="mt-auto border-t border-white/10 pt-4"><button className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-[13px] text-[#c7c9c9] hover:bg-white/10"><Settings2 size={16}/>Configurações</button><button className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-[13px] text-[#c7c9c9] hover:bg-white/10"><CircleHelp size={16}/>Central de ajuda</button><div className="mt-4 flex items-center gap-3 rounded-lg bg-white/10 p-3"><div className="grid size-8 place-items-center rounded-full bg-[#c5646d] text-[10px] font-bold text-white">GM</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-white">Gabriela Mendes</p><p className="text-[10px] text-[#a7adaa]">Gestora de operações</p></div><ChevronDown size={14} className="text-[#b4b8b7]"/></div></div>
    </aside>
    <section className="min-h-screen lg:pl-[258px]">
      <header className="sticky top-0 z-30 flex h-[70px] items-center border-b border-border bg-white/95 px-5 backdrop-blur sm:px-8"><button onClick={() => setMenu(true)} className="mr-3 lg:hidden"><Menu size={20}/></button><div className="relative hidden w-full max-w-[420px] sm:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#747a7a]" size={16}/><input placeholder="Buscar chamado, cliente ou pessoa" className="h-10 w-full rounded-md border border-border bg-[#f9f9f7] pl-10 text-xs placeholder:text-[#909594] focus:border-primary focus:outline-none"/></div><div className="ml-auto flex items-center gap-3"><button onClick={() => setPortalView(true)} className="hidden items-center gap-1.5 text-[10px] font-bold text-[#626a6b] hover:text-primary xl:flex"><PanelTop size={14}/>Portal do cliente</button><button className="relative grid size-9 place-items-center rounded-md border border-border text-[#566064]"><Bell size={17}/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary ring-2 ring-white"/></button><button className="hidden items-center gap-2 rounded-md bg-primary px-3.5 py-2.5 text-xs font-bold text-white shadow-[0_8px_18px_rgba(189,31,45,.2)] sm:flex"><Plus size={15}/>Novo chamado</button></div></header>
      <div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8 lg:px-10">
        <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 font-['DM_Mono'] text-[10px] uppercase tracking-[.14em] text-primary"><span className="size-1.5 rounded-full bg-primary"/> Central de operações ITIL</div><h1 className="font-['Newsreader'] text-[39px] font-medium leading-none tracking-[-.035em] text-[#202426] sm:text-[46px]">Visão da operação.</h1><p className="mt-3 text-[13px] text-muted-foreground">Terça-feira, 13 de outubro · Acompanhe serviços, chamados e compromissos.</p></div><div className="flex gap-2"><button className="flex items-center gap-2 rounded-md border border-border bg-white px-3 py-2.5 text-xs"><CalendarDays size={15}/>13–19 Out<ChevronDown size={14}/></button><button className="grid size-10 place-items-center rounded-md border border-border bg-white"><SlidersHorizontal size={16}/></button></div></div>
        <section className="mb-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Chamados ativos","24","+18%","esta semana",Activity],["SLA cumprido","92,4%","+2,8 p.p.","meta ≥ 90%",Gauge],["Tempo de resposta","42 min","− 8 min","média do período",Timer],["Horas pendentes","36,5h","9 lançamentos","para aprovação",Clock3]].map(([label,value,note,sub,Icon],i)=>{const I=Icon as typeof Activity;return <div key={String(label)} className="relative overflow-hidden rounded-lg border border-border bg-card p-5"><I size={18} className={i===0?"text-primary":"text-[#626a6b]"}/><p className="mt-5 text-[11px] font-semibold text-muted-foreground">{label as string}</p><p className="mt-1 font-['Newsreader'] text-[31px] leading-none tracking-[-.04em]">{value as string}</p><p className={`mt-3 font-['DM_Mono'] text-[10px] ${i===0?"text-primary":"text-[#707778]"}`}>{note as string} <span className="font-['Manrope'] text-muted-foreground">{sub as string}</span></p>{i===0&&<div className="absolute bottom-0 left-0 h-1 w-2/5 bg-primary"/>}</div>})}</section>
        <section className="mb-7 rounded-lg border border-border bg-card"><div className="flex flex-col gap-4 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-[15px] font-bold">Ciclo de vida de chamados</h2><p className="mt-1 text-[11px] text-muted-foreground">Classificação alinhada às práticas de gestão de serviços ITIL</p></div><button className="flex items-center gap-2 self-start rounded-md border border-border px-3 py-2 text-[11px] font-semibold text-[#525a5b]"><Layers3 size={14}/>Ver backlog</button></div><div className="grid divide-y divide-border md:grid-cols-5 md:divide-x md:divide-y-0">{lifecycle.map(([name,description,value,Icon,color])=>{const I=Icon;return <button key={name} className="group flex items-center gap-3 p-4 text-left hover:bg-[#fafafa] md:block"><span className="grid size-8 place-items-center rounded-md bg-[#f0f0ed]" style={{color}}><I size={16}/></span><div className="md:mt-4"><span className="text-xs font-bold">{name}</span><p className="mt-0.5 text-[10px] text-muted-foreground">{description}</p></div><span className="ml-auto font-['Newsreader'] text-[29px] md:mt-3 md:block md:ml-0" style={{color}}>{value}</span></button>})}</div></section>
        <div className="grid gap-7 xl:grid-cols-[minmax(0,1.7fr)_minmax(285px,.8fr)]"><section className="overflow-hidden rounded-lg border border-border bg-card"><div className="flex flex-col gap-4 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-[15px] font-bold">Chamados que pedem atenção</h2><p className="mt-1 text-[11px] text-muted-foreground">Prioridade, impacto e risco de SLA</p></div><div className="flex gap-2"><button className="flex items-center gap-1.5 rounded-md border border-border px-2.5 py-2 text-[11px]"><Filter size={13}/>Filtros</button><button className="rounded-md bg-[#353a3c] px-2.5 py-2 text-[11px] font-semibold text-white">Todos</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#f7f7f5] font-['DM_Mono'] text-[9px] uppercase tracking-[.12em] text-[#707676]"><tr><th className="px-5 py-3.5 font-normal">Chamado</th><th className="px-3 py-3.5 font-normal">Cliente</th><th className="px-3 py-3.5 font-normal">Classe ITIL</th><th className="px-3 py-3.5 font-normal">Responsável</th><th className="px-3 py-3.5 font-normal">SLA</th><th className="px-5 py-3.5 text-right font-normal">Situação</th></tr></thead><tbody>{tickets.map(([id,title,client,type,priority,owner,sla,status])=><tr key={id} className="border-t border-border hover:bg-[#fcfcfa]"><td className="px-5 py-4"><p className="font-['DM_Mono'] text-[10px] text-primary">{id}</p><p className="mt-1 max-w-[245px] truncate text-xs font-bold">{title}</p></td><td className="px-3 py-4 text-[11px] text-[#555d5e]">{client}</td><td className="px-3 py-4"><span className="text-[10px] font-semibold text-[#555d5e]">{type}</span><p className={`mt-1 text-[10px] ${priority==="Crítica"?"text-primary":"text-[#8c6b36]"}`}>{priority}</p></td><td className="px-3 py-4"><span className="grid size-6 place-items-center rounded-full bg-[#d9dcda] text-[8px] font-bold text-[#3c4445]">{owner}</span></td><td className="px-3 py-4 font-['DM_Mono'] text-[10px] text-[#5c6465]">{sla}</td><td className="px-5 py-4 text-right"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${status==="Aguardando cliente"?"bg-[#f2eadb] text-[#80662d]":status==="Em atendimento"?"bg-[#f7e7e8] text-[#9e1723]":"bg-[#e8ece9] text-[#3e5747]"}`}>{status}</span></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-border px-5 py-3"><span className="text-[10px] text-muted-foreground">Mostrando 5 de 24 chamados ativos</span><button className="flex items-center gap-1 text-[11px] font-bold text-primary">Acessar central<ArrowUpRight size={13}/></button></div></section>
          <aside className="space-y-7"><section className="rounded-lg border border-border bg-card p-5"><div className="flex justify-between"><div><h2 className="text-[15px] font-bold">Governança de serviço</h2><p className="mt-1 text-[11px] text-muted-foreground">Clientes & compromissos</p></div><MoreHorizontal size={18} className="text-muted-foreground"/></div><div className="mt-6 space-y-4"><div className="flex items-center justify-between border-b border-border pb-3"><div className="flex items-center gap-2 text-[11px]"><ShieldCheck size={15} className="text-primary"/>SLAs em risco</div><span className="font-['DM_Mono'] text-[12px] text-primary">03</span></div><div className="flex items-center justify-between border-b border-border pb-3"><div className="flex items-center gap-2 text-[11px]"><Building2 size={15} className="text-[#5d6869]"/>Clientes com chamados</div><span className="font-['DM_Mono'] text-[12px]">08</span></div><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-[11px]"><BookOpen size={15} className="text-[#5d6869]"/>Baselines atualizadas</div><span className="font-['DM_Mono'] text-[12px]">12/14</span></div></div><button onClick={()=>setSelected("SLA & Baseline")} className="mt-5 flex w-full items-center justify-center gap-2 rounded-md border border-border py-2.5 text-[11px] font-bold text-[#4d5657] hover:border-primary hover:text-primary">Gerenciar SLA & Baseline<ChevronRight size={14}/></button></section><section className="rounded-lg bg-[#2c3032] p-5 text-white"><div className="flex items-center gap-2 text-[#ef747c]"><ClipboardCheck size={17}/><span className="font-['DM_Mono'] text-[10px] uppercase tracking-[.12em]">Aprovações</span></div><p className="mt-4 text-[14px] font-bold">36,5 horas aguardam revisão</p><p className="mt-1 text-[11px] leading-relaxed text-[#c8cccc]">9 lançamentos de 5 analistas precisam de sua aprovação.</p><button className="mt-4 flex items-center gap-1.5 text-[11px] font-bold text-white">Revisar horas<ChevronRight size={14}/></button></section></aside></div>
        <section className="mt-7 grid gap-7 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-[15px] font-bold">Esforço registrado</h2><p className="mt-1 text-[11px] text-muted-foreground">Horas por período · outubro</p></div><div className="flex rounded-md bg-[#f0f0ed] p-0.5">{["Semana","Mês"].map(x=><button onClick={()=>setPeriod(x)} key={x} className={`rounded px-2.5 py-1.5 text-[10px] font-semibold ${period===x?"bg-white text-primary shadow-sm":"text-muted-foreground"}`}>{x}</button>)}</div></div><div className="mt-7 flex h-[116px] items-end gap-2 border-b border-border">{[38,55,44,72,58,87,64,80,52,91,70,100].map((v,i)=><div key={i} className="flex h-full flex-1 items-end"><div className={`w-full rounded-t-sm ${i===11?"bg-primary":"bg-[#bcc1be]"}`} style={{height:`${v}%`}}/></div>)}</div><div className="mt-2 flex justify-between font-['DM_Mono'] text-[9px] text-muted-foreground"><span>01 OUT</span><span>08 OUT</span><span>15 OUT</span><span>22 OUT</span><span>29 OUT</span></div></div><div className="rounded-lg border border-border bg-card p-5"><h2 className="text-[15px] font-bold">Sugestão de melhoria</h2><p className="mt-1 text-[11px] text-muted-foreground">Próximo passo recomendado</p><div className="mt-5 border-l-2 border-primary pl-4"><p className="text-[12px] font-bold">Criar uma visão dedicada de Problemas</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Inclua causa raiz, workaround e vínculo com incidentes recorrentes para reforçar a prática ITIL.</p><button className="mt-3 flex items-center gap-1 text-[11px] font-bold text-primary">Ver estrutura sugerida<ChevronRight size={13}/></button></div></div></section>
      </div>
    </section>
  </main>;
}
